export const manufacturers: string[] = [
    "Toyota",
    "Volkswagen",
    "Ford",
    "Honda",
    "Nissan",
    "Chevrolet",
    "BMW",
    "Mercedes-Benz",
    "Audi",
    "Hyundai",
    "Kia",
    "Subaru",
    "Mazda",
    "Lexus",
    "Jeep",
    "Volvo",
    "Porsche",
    "Tesla",
    "Ferrari",
    "Lamborghini",
    "Bentley",
    "Rolls-Royce",
    "Aston Martin",
    "Maserati",
    "Alfa Romeo",
    "Fiat",
    "Chrysler",
    "Dodge",
    "Jaguar",
    "Land Rover",
    "Infiniti",
    "Acura",
    "Cadillac",
    "GMC",
    "Buick",
    "Lincoln",
    "Ram",
    "Mini",
    "Smart",
    "Suzuki",
    "Daihatsu",
    "Foton",
    "Haval",
    "Geely",
    "Great Wall",
    "Chery",
    "BYD",
    "NIO",
    "Xpeng Motors",
    "Li Auto",
    "WM Motor",
    "SAIC Maxus",
    "GAC Group",
    "Neta",
    "XPeng Motors",
    "Leopaard Motors"
  ]